# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version = 1.0.3
maven_group = dev.phonis
archives_base_name = sharedwaypoints-server-mod

# Dependencies
fabric_version=0.153.0+26.2
