# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.1
loader_version=0.18.5
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version = 1.0.3
maven_group = dev.phonis
archives_base_name = sharedwaypoints-server-mod

# Dependencies
fabric_version=0.144.3+26.1
